// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkrATeZ1PYwjTVPGLWzzOUGyN4w0M_fq8',
    appId: '1:950386226484:web:7011a9199030253bfc2161',
    messagingSenderId: '950386226484',
    projectId: 'twins-app-ab1a5',
    authDomain: 'twins-app-ab1a5.firebaseapp.com',
    databaseURL: 'https://twins-app-ab1a5-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'twins-app-ab1a5.appspot.com',
    measurementId: 'G-5VEJ1XTSPM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5e_eEeHdYQnNpt_dp9C1OzKVUgYGR_OE',
    appId: '1:950386226484:android:33633eccc88b444dfc2161',
    messagingSenderId: '950386226484',
    projectId: 'twins-app-ab1a5',
    databaseURL: 'https://twins-app-ab1a5-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'twins-app-ab1a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvBHsMfC5D59anOWZqfNF3icmzoYppEbw',
    appId: '1:950386226484:ios:67a2cc9faab51fbffc2161',
    messagingSenderId: '950386226484',
    projectId: 'twins-app-ab1a5',
    databaseURL: 'https://twins-app-ab1a5-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'twins-app-ab1a5.appspot.com',
    iosBundleId: 'com.twins.twinsFront',
  );
}
